### ISSUE TITLE
SourceXtractor++ installation in Ubuntu 20.0.4 fails

### ISSUE THREAD

**Issue by mkuemmel** [astrorama/Elements#4]
When installing SE++ (as an Elements project) with the usual:
`$mkdir build`
`cd build`
`cmake ..`
`make all`
`make install`
`sourcextractor++` won't be installed properly but lead to a python error when running on data. But SE++ can be run by prepending the command 'run' from the build directory, such as:
`<path_to_build_dir>/run sourcextractor++ --config .....`

**Comment by degauden** [comment]
Yes. This is a problem in Elements. I am looking into it.
