### ISSUE TITLE
Tagging 6.0.1

### ISSUE THREAD

**Issue by mkuemmel** [astrorama/Elements#6]
Alexandria 2.23.0 depends on Elements 6.0.1, and also for Euclid we'll need an SE++ depending on Elements 6.0.1. Is it possible to have it tagged also in github?

**Comment by degauden** [comment]
Yes. For sure. My bad

**Comment by degauden** [comment]
It should now be available : https://github.com/astrorama/Elements/releases/tag/6.0.1
